version: '3'
services:
  server:
    build: ./server
    environment:
      - LOTTERY_DB_USER
      - LOTTERY_DB_PASSWORD
      - LOTTERY_DB_NAME
      - LOTTERY_DB_HOST=db
      - LOTTERY_SERVER_PORT=80
      - LOTTERY_SERVER_HOST
    restart: always
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - LOTTERY_SERVER_HOST=${LOTTERY_SERVER_HOST}
    restart: always
  db:
    build: ./db
    environment:
      - POSTGRES_DB=${LOTTERY_DB_USER}
      - POSTGRES_USER=${LOTTERY_DB_USER}
      - POSTGRES_PASSWORD=${LOTTERY_DB_PASSWORD}
    volumes:
      - lottery-db-data:/var/lib/postgresql/data
    restart: always
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    restart: always

volumes:
  lottery-db-data:
